name: CI
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 14.x
        uses: actions/setup-node@master
        with:
          version: 14.x

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn jest
  types:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 14.x
        uses: actions/setup-node@master
        with:
          version: 14.x

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install Dependencies
        run: yarn

      - name: Check Types
        run: yarn tsc
